name: User profile data service
description: |
    
style: RESOURCE
uriTemplate: /auth/profile
methods:
    GET:
        summary: Get one User profile data
        notes: Get one User profile data
        # implementation: api.getUser profile data
        request:
            parameters: []
            cookies: []
            headers:
                -
                    field: Accept
                    content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                -
                    field: Accept-Encoding
                    content: "gzip, deflate"
        responses:
            -
                name: OK
                statusCode: &OkStatusCode 200
                reason: &OkReason Successful execution
                # validationSchema: getResource-responseBody-validationSchema.json
                cookies: []
                headers:
                    -
                        field: Content-Type
                        content: application/json
                mockBody: getResource-responseBody.json
        testCases:
            -
                name: Get User profile data
                description: Successfully retrieves one customer
                url: /auth/profile
                template: testGetMethod.js
                request:
                    cookies: []
                    headers:
                        -
                            field : "Accept"
                            content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                        -
                            field: "Accept-Encoding"
                            content: "gzip, deflate"
                response:
                    name: OK
                    statusCode: *OkStatusCode
                    reason: *OkReason
                    cookies: []
                    headers:
                        -
                            field: "Content-Type"
                            content: "application/json"
                    # validationSchema: getResource-responseBody-validationSchema.json

    DELETE:
        summary: Delete a User profile data
        notes: Delete a User profile data
        # implementation: api.deleteUser profile data
        request:
            parameters: 
                -
                    name: id
                    kind: QUERY
                    required: true
                    type: number
                    summary: The id of the User profile data to be deleted
                    default: 1
            cookies: []
            headers:
                -
                    field: Accept
                    content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                -
                    field: Accept-Encoding
                    content: "gzip, deflate"
        responses:
            -
                name: OK
                statusCode: *OkStatusCode
                reason: *OkReason
                # validationSchema: deleteResource-responseBody-validationSchema.json
                cookies: []
                headers:
                    -
                        field: Content-Type
                        content: application/json
                mockBody: deleteResource-responseBody.json
        testCases:
            -
                name: Delete User profile data
                description: Successfully delete the User profile data
                url: /auth/profile/1
                template: testDelMethod.js
                request:
                    cookies: []
                    headers:
                        -
                            field : "Accept"
                            content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                        -
                            field: "Accept-Encoding"
                            content: "gzip, deflate"
                response:
                    name: OK
                    statusCode: *OkStatusCode
                    reason: *OkReason
                    cookies: []
                    headers:
                        -
                            field: "Content-Type"
                            content: "application/json"

    PUT:
        summary: Update a User profile data
        notes: Update a User profile data
        # implementation: api.putUser profile data
        request:
            parameters:
                -
                    name: id
                    kind: QUERY
                    required: true
                    type: number
                    summary: The id of the User profile data to be updated
                    default: 1
            cookies: []
            headers:
                -
                    field: Accept
                    content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                -
                    field: Accept-Encoding
                    content: "gzip, deflate"
        responses:
            -
                name: OK
                statusCode: *OkStatusCode
                reason: *OkReason
                # validationSchema: putResource-responseBody-validationSchema.json
                cookies: []
                headers:
                    -
                        field: Content-Type
                        content: application/json
                mockBody: putResource-responseBody.json
        testCases:
            -
                name: Update User profile data
                description: Succesfully updates a User profile data
                url: /auth/profile/1
                template: testPutMethod.js
                request:
                    cookies: []
                    headers:
                        -
                            field : "Accept"
                            content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                        -
                            field: "Accept-Encoding"
                            content: "gzip, deflate"
                    body: putResource-requestBody.json
                response:
                    name: OK
                    statusCode: *OkStatusCode
                    reason: *OkReason
                    cookies: []
                    headers:
                        -
                            field: "Content-Type"
                            content: "application/json"
                    body: putResource-responseBody.json
                    # validationSchema: putResource-responseBody-validationSchema.json
